version: "3.9"

x-logging: &logging
  driver: "fluentd"
  options:
    fluentd-address: 10.116.0.4:24224

services:
  agent:
    hostname: sql-agent
    restart: unless-stopped
    image: docker.elastic.co/beats/elastic-agent:8.1.2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    user: root
    environment:
      - FLEET_ENROLL=1
      - FLEET_ENROLLMENT_TOKEN=SGdwejdYOEJkNGFFZmg4QWNrNEY6OFRnMElJVW5TS2lhUHk4S00tX1REZw==
      - FLEET_URL=https://10.116.0.4:8220
      - FLEET_INSECURE=1
  db:
    logging: *logging
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=&52#Z3#^2D@Fv!
    volumes:
      - /var/opt/mssql:/var/opt/mssql
    ports:
      - "1433:1433"