version: "3.9"
networks:
  compile-network:
    driver: bridge
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.web
      args:
        ASPNETCORE_ENVIRONMENT: Development
    ports:
    - "44377:80"
    networks:
    - compile-network
  goapi:
    build:
      context: ./go-api
      dockerfile: Dockerfile
    ports:
    - "8081:8081"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      compile-network:
        aliases:
          - "goapi"
#  db:
#    image: mcr.microsoft.com/mssql/server:2019-latest
#    environment:
#      - ACCEPT_EULA=y
#      - SA_PASSWORD=!Password1!
#    ports: 
#      - "1433:1433"