version: "3.9"
networks:
  compile-network:
    driver: bridge
services:
  api:
    depends_on:
      - db
    build:
      context: ./api
      dockerfile: Dockerfile.web
    image: registry.digitalocean.com/code-editor-images/code-editor-api:dev
    ports:
    - "8080:80"
    networks:
    - compile-network
  goapi:
    build:
      context: ./go-api
      dockerfile: Dockerfile
    image: registry.digitalocean.com/code-editor-images/code-editor-go-api:dev
    ports:
    - "8081:8081"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - compile-network
  db:
    build:
      context: ./api
      dockerfile: Dockerfile.db
    image: registry.digitalocean.com/code-editor-images/code-editor-db:dev