version: "3"
services:
  fluentd:
    restart: unless-stopped
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"
  metrics:
    restart: unless-stopped
    container_name: metrics
    image: docker.elastic.co/beats/elastic-agent:8.1.2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    user: root
    environment:
      - FLEET_ENROLL=1
      - FLEET_ENROLLMENT_TOKEN=N0Q4TzdYOEJ5RFNJb1NaWG5xZ0c6elEtRzVPLWVUXy1tZ3doOXRLUDNOQQ==
      - FLEET_URL=https://agent:8220
      - FLEET_INSECURE=1
  agent:
    restart: unless-stopped
    container_name: agent
    image: docker.elastic.co/beats/elastic-agent:8.1.2
    links:
      - "elasticsearch"
    expose:
      - "8220"
    ports:
      - "8220:8220"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    user: root
    environment:
      - FLEET_SERVER_ENABLE=true
      - FLEET_ENROLL=1
      - FLEET_ENROLLMENT_TOKEN=UnNQQTdIOEJWRVRTbFJnQTF3YTk6cmlHX3FQSG1UYXU1U2V5b3laa1Y0UQ==
      - FLEET_URL=https://localhost:8220
      - FLEET_SERVER_POLICY_ID=fleet-server-policy
      - FLEET_SERVER_ELASTICSEARCH_HOST=https://elasticsearch:9200
      - FLEET_SERVER_SERVICE_TOKEN=AAEAAWVsYXN0aWMvZmxlZXQtc2VydmVyL3Rva2VuLTE2NDg5NDQ1NjA5OTc6Tzk2dFZkUEpRa3kyYnJfRmF3QWFuQQ
      - FLEET_SERVER_INSECURE_HTTP
    
  elasticsearch:
    restart: unless-stopped
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=true
      - xpack.security.authc.api_key.enabled=true
      - ELASTIC_PASSWORD=QCNxSe}u6)}{]2v#
    volumes:
      - es_data:/usr/share/elasticsearch/data
    expose:
      - "9200"
    ports:
      - "9200:9200"
    mem_limit: 2g

  kibana:
    restart: unless-stopped
    image: docker.elastic.co/kibana/kibana:8.1.2
    links:
      - "elasticsearch"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=M&9D87?TPv!NUFnr
      - SERVER_PUBLICBASEURL=https://kibana.siucode.io
    ports:
      - "5601:5601"
volumes:
  es_data: