version: "3"
x-logging: &logging
  driver: "fluentd"
  options:
    fluentd-address: localhost:24224

services:
  fluentd:
    restart: unless-stopped
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"
  agent:
    hostname: logging-agent
    restart: unless-stopped
    image: docker.elastic.co/beats/elastic-agent:8.1.2
    links:
      - "elasticsearch"
    expose:
      - "8220"
    ports:
      - "8220:8220"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    user: root
    environment:
      - FLEET_SERVER_ENABLE=true
      - FLEET_ENROLL=1
      - FLEET_URL=https://localhost:8220
      - FLEET_SERVER_POLICY_ID=fleet-server-policy
      - FLEET_SERVER_ELASTICSEARCH_HOST=http://elasticsearch:9200
      - FLEET_SERVER_SERVICE_TOKEN=AAEAAWVsYXN0aWMvZmxlZXQtc2VydmVyL3Rva2VuLTE2NDg5NTYwOTY4MzI6TWNOa1RYMkhUWmVmc09zNTRaVEMxZw
      - FLEET_SERVER_INSECURE_HTTP
    
  elasticsearch:
    logging: *logging
    restart: unless-stopped
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=true
      - xpack.security.authc.api_key.enabled=true
      - ELASTIC_PASSWORD=QCNxSe}u6)}{]2v#
    volumes:
      - es_data:/usr/share/elasticsearch/data
    expose:
      - "9200"
    ports:
      - "9200:9200"
    mem_limit: 2g

  kibana:
    logging: *logging
    restart: unless-stopped
    image: docker.elastic.co/kibana/kibana:8.1.2
    links:
      - "elasticsearch"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=M&9D87?TPv!NUFnr
      - SERVER_PUBLICBASEURL=https://kibana.siucode.io
      - xpack.encryptedSavedObjects.encryptionKey=0f9fa0780e614093c0813d3063afa7df
      - xpack.reporting.encryptionKey=fe622f672ceb6edb5545122809474bec
      - xpack.security.encryptionKey=1b3567c43396dea7fc4b51a4cd329b8c
    ports:
      - "5601:5601"
volumes:
  es_data: