name: Deploy Dev

on: workflow_dispatch

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    env:
      API_URL: registry.digitalocean.com/code-editor-images/code-editor-api:dev
      DB_URL: registry.digitalocean.com/code-editor-images/code-editor-db:dev
        
    steps:
    - uses: actions/checkout@v2
    - name: Builds Images
      run: docker compose -f docker-compose.dev.yml build
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with: 
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    - name: Log Into DO Container Registry
      run: doctl registry login --expiry-seconds 600
    - name: Push images to DO Container Registry
      run: docker compose -f docker-compose.dev.yml push
    - name: Deploy to Dev
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          docker login registry.digitalocean.com -u ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }} -p ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          cd code-editor
          git pull
          docker-compose -f docker-compose.dev.yml pull
          docker-compose -f docker-compose.dev.yml up --detach
          docker image prune -f
          

      

      
