name: Deploy Dev

on: workflow_dispatch

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
        
    steps:
    - uses: actions/checkout@v2
    - uses: satackey/action-docker-layer-caching@v0.0.11
      # Ignore the failure of a step and avoid terminating the job.
      continue-on-error: true
    - name: Builds api Image
      run: docker build . --file Dockerfile.web -t registry.digitalocean.com/code-editor-images/code-editor-api:$(git rev-parse --short HEAD)
    - name: Builds DB Image
      run: docker build . --file Dockerfile.db -t registry.digitalocean.com/code-editor-images/code-editor-db:$(git rev-parse --short HEAD)
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with: 
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    - name: Log Into DO Container Registry
      run: doctl registry login --expiry-seconds 600
    - name: SSH into dev
      run: doctl compute ssh BackendApi
#    - name: Push images to DO container registry
#      run: |
#        docker push registry.digitalocean.com/code-editor-images/code-editor-api:$(git rev-parse --short HEAD)
#        docker push registry.digitalocean.com/code-editor-images/code-editor-db:$(git rev-parse --short HEAD)
      

      
