name: Deploy Dev

on: workflow_dispatch

jobs:
  deploy_logging:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy To Logging Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_LOGGING }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY_LOGGING}}
        script: |
          ls code-editor
          docker-compose --version
          

      

      
