name: Deploy Dev

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Builds api Image
      run: docker build api/. --file Dockerfile.web --t registry.digitalocean.com/code-editor-images/code-editor-api:$(date +%s)
    - name: Builds DB Image
      run: docker build api/. --file Dockerfile.db code-editor-db --tag registry.digitalocean.com/code-editor-images/code-editor-db:$(date +%s)
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with: 
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    - name: Log Into DO Container Registry
      run: doctl registry login --expiry-seconds 600
    - name: Push images to DO container registry
      run: |
        docker push registry.digitalocean.com/code-editor-images/code-editor-api$(date +%s)
        docker push registry.digitalocean.com/code-editor-images/code-editor-db:$(date +%s)
      

      
